export const Repositories = {
  UserRepository: 'UserRepository',
  AuthorizedUserRepository: 'AuthorizedUserRepository',
  TicketRepository: 'TicketRepository',
  TransactionRepository: 'TransactionRepository',
  RedemptionRepository: 'RedemptionRepository',
  ReportRepository: 'ReportRepository',
  FoodstuffRepository: 'FoodstuffRepository',
  FoodstuffHistoryRepository: 'FoodstuffHistoryRepository',
  CookedFoodNameRepository: 'CookedFoodNameRepository',
  CookedFoodRepository: 'CookedFoodRepository',
  FoodstuffRequisitionRepository: 'FoodstuffRequisitionRepository',
  WalletRepository: 'WalletRepository',
  OrderRepository: 'OrderRepository',
  StudentRepository: 'StudentRepository',
  MedicalRecordRepository: 'MedicalRecordRepository',
  MedicalWalletRepository: 'MedicalWalletRepository',
};
